### ISSUE TITLE
Can't import this package to Unity Project.

### ISSUE THREAD

**Issue by jeffreyyong** [SaladLab/Json.Net.Unity3D#10]
Hi,

Thanks for the great open source project. I am wondering why I am not able to import this package into my project? May I know what are the right steps to do it?

Regards,
Jeffrey

**Comment by IceflowRE** [comment]
Idk what are you doing wrong, but it works perfectly with Unity 5.3 and 5.4.
You can drag and drop the unity packages into the assets folder or `Assets-> Import Package -> Costum Package...`

**Comment by veblush** [comment]
@jeffreyyong More information about your problem will be helpful such as Unity version, how to import, and error messages you encountered.

**Comment by jeffreyyong** [comment]
Hi thank you for the reply. I managed to import the package now.
