### ISSUE TITLE
JPath not removed?

### ISSUE THREAD

**Issue by TheOddler** [SaladLab/Json.Net.Unity3D#2]
In the description, where you describe what's been done, is stated that JPath has been removed:

> Remove JPath class to reduce size of DLL.

However, when I look in the repo (`\src\Newtonsoft.Json\Linq\JsonPath`), `JPath.cs` and everything for jpath is still there.

Am I looking at this wrong?

**Comment by veblush** [comment]
Yes. There are source files you mentioned. But those files are excluded at project file and not included for building library. I decided to keep those files even it is not necessary because it makes further merging from [upstream](https://github.com/JamesNK/Newtonsoft.Json) easier.

**Comment by TheOddler** [comment]
Ok, so if I use the source directly (rather than the dlls) I will be able to use JsonPath?

**Comment by veblush** [comment]
Maybe possible but some works might be required to use JsonPath. For example, `SelectTokens` method of `JToken` was commented out so you need to revert it to use it again.

**Comment by veblush** [comment]
The reason that I removed Json.Path from Unity3D at the first time was the matter of size of DLL. But now we have a lite version of json.net for Unity3D so I decided to get this back for normal version. From [this release](https://github.com/SaladLab/Json.Net.Unity3D/releases/tag/8.0.2.JsonPath), you can use JsonPath.

**Comment by TheOddler** [comment]
Awesome! You've done a great job, and thanks a lot for that!
