### ISSUE TITLE
What's the difference between jsonnet.lite and jsonnet  package?

### ISSUE THREAD

**Issue by wangjianpeng** [SaladLab/Json.Net.Unity3D#23]
Should i import both packages to my unity project ? or just choose one package with my need ?

**Comment by master-lincoln** [comment]
Isn't the Readme clear enough on this?

> For Unity.Lite version, additional works are done to make more lite.
>
>Remove JsonLinq, JPath (JToken, ...)
>Remove Bson

So if you do not intend to use these features you choose the Lite version.
Otherwise you have to use the full version
