### ISSUE TITLE
Don't support UWP project

### ISSUE THREAD

**Issue by ChangweiZhang** [SaladLab/Json.Net.Unity3D#4]
I have tried your unity dll library, and it works perfect on PC. But it failed when I try build my unity project to UWP project. The errors look like this:

![default](https://cloud.githubusercontent.com/assets/4610610/15319537/e625c888-1c5d-11e6-8497-3c21585ef30f.PNG)

**Comment by veblush** [comment]
Oh, thanks for reporting! Because I have never tried UWP, I didn't know this issue before 😄. For hotfix, please read [Workaround for UWP](https://github.com/SaladLab/Json.Net.Unity3D/blob/master/docs/UwpWorkaround.md) and try to do what it says.
