### ISSUE TITLE
Don't support Mono2x?

### ISSUE THREAD

**Issue by DieJob** [SaladLab/Json.Net.Unity3D#5]
Thanks for your great work! It's very useful for me. But when I change Scripting Backend to Mono2x on iOS platform, it can't work.

**Comment by veblush** [comment]
Thanks for reporting. Could you tell me details of your problem? (Unity version, error message, etc)
It should be working under iOS because it's the primary target.

**Comment by DieJob** [comment]
Thank you for your reply. My Unity version is 5.3.5f1 and error message as shown in Figure
![img_0003](https://cloud.githubusercontent.com/assets/7467175/16476398/abccfbec-3eb9-11e6-9188-a347f6934dc5.PNG)

**Comment by veblush** [comment]
Ok. At first, please make sure that your project has a [link.xml](https://github.com/SaladLab/Json.Net.Unity3D/blob/master/src/UnityPackage/Assets/link.xml) at your project's asset folder. It's a must-have file to keep json.net work well under IL2CPP envroment like iOS. 

And if possible, let me know what data structure you want to (de)serialize from text. It will help a lot.

**Comment by DieJob** [comment]
Maybe my poor english let you misunderstand my meaning. There are some reasons that I need use your project under Mono2x envroment on iOS platform and it works well under IL2CPP envroment.

My data just like this
{
     "10001" : {
            "id" : 10001,
            "name" : tom,
            "age" : 16
     },
     .......
}

**Comment by veblush** [comment]
Oh I got it. When I read your first writing, my eye automatically translated mono2x to IL2CPP. 😉 
Mono2x has been deprecated already after IL2CPP was introduced and it has a few subtle bugs of handling generic code which are important for json.net to work well on iOS. Because of this, mono2x is not supported anymore. Please use IL2CPP instead of mono2x on iOS even it's a way slow. 😉

**Comment by veblush** [comment]
I close this issue because previous reopening looks a mistake click. If not, please reopen it and write a comment.
